### PR TITLE
Gatttool script and GShock protocol description

### PR DESCRIPTION
**Pull request by harlock974**

### CODE REVIEW

**Comment by izivkov** [comment]
Hey @harlock974 , looks like you have done a lot of good work on this PR. I think we can merge after making these small changes I commented on.

**Comment by harlock974** [comment]
Where can I see your comment ? (sorry I'm not used to do large commits)

**Comment by izivkov** [comment]
https://github.com/izivkov/GShockTimeServer/pull/5

**Comment by izivkov** [comment]
Go to the Pull Request, and select "Conversations"

**Comment by izivkov** [comment]
I merged your pull request, but I think people will not be aware of your scripts. Can you also add a few lines in the main [README](https://github.com/izivkov/GShockTimeServer/blob/main/README.rst) file describing your script and its location.

**Comment by harlock974** [comment]
Good idea I'll do that.

**Pull request merged**
